CLCV_ROOT = /net/per920a/export/das14a/satoh-lab/plsang
CLCV_CORPORA_ROOT = $(CLCV_ROOT)/corpora
DATA_ROOT = ./data

MSCOCO_SYM = Microsoft_COCO
MSCOCO_ROOT = $(CLCV_CORPORA_ROOT)/$(MSCOCO_SYM)
MSCOCO_DATA_ROOT = $(DATA_ROOT)/$(MSCOCO_SYM)


cv-l1:	
	CUDA_VISIBLE_DEVICES=4 th cv_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -ft_lr_mult 10 -num_test_image 1000 \
		-print_log_interval 100 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 -reg_type 1 -max_cv_iters 1000 \
		2>&1 | tee log/cv/train_b4_milmaxnor_multitask_mt1_l1.log
cv-l2:	
	CUDA_VISIBLE_DEVICES=4 th cv_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -ft_lr_mult 10 -num_test_image 1000 \
		-print_log_interval 100 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 -reg_type 2 -max_cv_iters 1000 \
		2>&1 | tee log/cv/train_b4_milmaxnor_multitask_mt1_l2.log
cv-l21:	
	CUDA_VISIBLE_DEVICES=7 th cv_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adaml21 -ft_lr_mult 10 -num_test_image 1000 \
		-print_log_interval 100 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 -reg_type 3 -max_cv_iters 1000 \
		2>&1 | tee log/cv/train_b4_milmaxnor_multitask_mt1_l21_cont.log

multitask-milmaxnor-mt1-l2:	
	CUDA_VISIBLE_DEVICES=4 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -test_interval 1000 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 1 -bias_init -6.58 -model_type milmaxnor -weight_decay 0.0001 -multitask_type 1 -reg_type 2 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1_wd0.0001_l2.log

multitask-milmaxnor-mt1-b4:	
	CUDA_VISIBLE_DEVICES=1 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -test_interval 1000 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 1 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1.log
multitask-milmaxnor-mt1-l21-w5:	
	CUDA_VISIBLE_DEVICES=4 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adaml21 -test_interval 100 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 10 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 \
		-reg_type 3 -weight_decay 1e-5 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1_l21_w5.log
multitask-milmaxnor-mt1-l21-w6:	
	CUDA_VISIBLE_DEVICES=6 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adaml21 -test_interval 100 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 10 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 \
		-reg_type 3 -weight_decay 1e-6 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1_l21_w6.log
multitask-milmaxnor-mt1-l21-w4:	
	CUDA_VISIBLE_DEVICES=7 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adaml21 -test_interval 100 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 10 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 \
		-reg_type 3 -weight_decay 1e-4 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1_l21_w4.log
multitask-milmaxnor-mt2:	
	CUDA_VISIBLE_DEVICES=5 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 2 -optim adam -test_interval 1000 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 1 -bias_init -6.58 -model_type milmaxnor -multitask_type 2 \
		2>&1 | tee log/train_b2_milmaxnor_multitask_mt2.log

multitask-milmaxnor-mt2-b4:	
	CUDA_VISIBLE_DEVICES=4 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -test_interval 1000 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 1 -bias_init -6.58 -model_type milmaxnor -multitask_type 2 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt2.log
multitask-milnor-mt1-b4:	
	CUDA_VISIBLE_DEVICES=1 th train_multitask.lua -coco_data_root /net/per610a/export/das11f/plsang/codes/clcv/resources/data/Microsoft_COCO \
                -cnn_proto /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers_deploy.prototxt \
                -cnn_model /net/per920a/export/das14a/satoh-lab/plsang/very_deep/caffe/VGG_ILSVRC_16_layers.caffemodel \
		-train_image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 \
		-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
		-batch_size 4 -optim adam -test_interval 100 -ft_lr_mult 10 -num_test_image 400 \
		-print_log_interval 1 -bias_init -6.58 -model_type milmaxnor -multitask_type 1 \
		2>&1 | tee log/train_b4_milmaxnor_multitask_mt1_tmp.log
multitask-test:
	CUDA_VISIBLE_DEVICES=1 th test_multitask.lua -log_mode file -test_cp cp/model_multitask_milmaxnor_mt2_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
			-model_type milmaxnor -print_log_interval 1000

extract:
	CUDA_VISIBLE_DEVICES=1 th extract_features.lua -log_mode console -test_cp cp/model_multitask_milmaxnor_mt1_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
			-batch_size 8 \
			-output_file $(MSCOCO_DATA_ROOT)/mscoco2014_val_depnet_mydepsv4.h5 \
			-model_type milmaxnor -num_target 22034 -print_log_interval 1000
extract-med:
	CUDA_VISIBLE_DEVICES=7 th extract_features_med.lua -log_mode console -test_cp cp/model_multitask_milmaxnor_mt1_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-batch_size 8 \
			-output_file $(MSCOCO_DATA_ROOT)/mscoco2014_med_depnet_fc6.h5 -layer fc6 \
			-model_type milmaxnor -num_target 22034 -num_test_video 5 
extract-fc7:
	CUDA_VISIBLE_DEVICES=7 th extract_features.lua -log_mode console -test_cp cp/model_multitask_milmaxnor_mt1_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-val_image_file_h5 data/mscoco2014_val_preprocessedimages_msmil.h5 \
			-batch_size 8 -layer fc7 \
			-output_file $(MSCOCO_DATA_ROOT)/mscoco2014_val_depnet_mydepsv4fc7.h5 \
			-model_type milmaxnor -num_target 22034 -print_log_interval 1000
extract-train-fc7:
	CUDA_VISIBLE_DEVICES=3 th extract_features.lua -log_mode console -test_cp cp/model_multitask_milmaxnor_mt1_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 -label_file_h5 mscoco2014_train_myconceptsv3.h5 \
			-batch_size 8 -layer fc7 \
			-output_file $(MSCOCO_DATA_ROOT)/mscoco2014_train_depnet_mydepsv4fc7.h5 \
			-model_type milmaxnor -num_target 22034 -print_log_interval 1000
extract-train-fc8:
	CUDA_VISIBLE_DEVICES=2 th extract_features.lua -log_mode console -test_cp cp/model_multitask_milmaxnor_mt1_adam_b4_bias-6.580000_lr0.000010_epoch2.t7 \
			-image_file_h5 data/mscoco2014_train_preprocessedimages_msmil.h5 -label_file_h5 mscoco2014_train_myconceptsv3.h5 \
			-batch_size 8 \
			-output_file $(MSCOCO_DATA_ROOT)/mscoco2014_train_depnet_mydepsv4fc8.h5 \
			-model_type milmaxnor -num_target 22034 -print_log_interval 1000
